graph TB
    requests([requests])
    config
    commands([commands])
    cli
    dependencies
    handlers
    factory
    services
    storage
    datastore[(datastore)]

    requests --> dependencies
    requests --> handlers
    dependencies --> handlers
    handlers --> services
    services --> storage
    storage --> datastore

    config --> factory
    factory --> handlers

    commands --> cli
    factory --> cli
    cli --> services
